# Menu like notepad
from tkinter import *
m = Tk()
m.title("Abhi")
menu = Menu(m)
m.config( menu = menu)
filemenu = Menu(menu)
menu.add_cascade(label = 'File', menu=filemenu)
filemenu.add_command(label="New Tab")
filemenu.add_command(label="New Window")
filemenu.add_command(label="OPen")
filemenu.add_command(label="Recent")
filemenu.add_command(label="Save")
filemenu.add_command(label="Save AS")
filemenu.add_command(label="Save All")
filemenu.add_separator()
filemenu.add_command(label="Page Setup")
filemenu.add_command(label="Exit")

helpmenu = Menu(menu)
menu.add_cascade(label="Edit",menu=helpmenu)
helpmenu.add_command(label="Undo")
helpmenu.add_command(label="cut")
helpmenu.add_command(label="Copy")
helpmenu.add_command(label="Past")
helpmenu.add_command(label="Delete")
filemenu.add_separator()
helpmenu.add_command(label="Find")
helpmenu.add_command(label="Findnext")
helpmenu.add_command(label="FindPrivios")

viewmenu = Menu(menu)
menu.add_cascade(label="View",menu=viewmenu)
viewmenu.add_command(label = "Zoom")
viewmenu.add_command(label = "Status Bar")
viewmenu.add_command(label = "Word Wrap")
m.mainloop()